- Python/left_rotate.py
Added left rotation of an array program in Python
> added left rotation of array

- C/binarysearch.c
Reverts Ayroid/Coding-Practice-Problems#10
> Revert "Update binarysearch.c"

- C/Factorial.c
I've added a C program for finding factorial with recursion.
> Created Factorial.c file

- java/code_1.java
This is my First Commit.
Thank you for guiding me, sir.
> First Commit

- java/linearSearch.java
Fixed a line that is causing the threating issue.
Thank me later.
> Changed in linear search

- c++/optimizedsort012.cpp
I'd love to contribute to your repository.
> Fourth Commit

- Python/walk.py
> Python first commit

- java/pallindrome.java
> Pallindrome number

- c++/Longest_Increasing_Subsequence.cpp
Time Complexity : O(n^2)
Space Complexity : O(n)
> Longest Increasing Subsequence

- java/Addition.java
- java/Addition2.java
> New Commit

- Combination.java
> Java program to implement combinations

- java/MatrixMul.java
- java/accessspecifiers.java
- java/overload.java
- java/passingbyref.java
- java/passingbyvalues.java
- java/polymorphism.java
- java/retobj.java
- java/retvalue.java
- java/singinherit.java
- java/twoconst.java
- java/usestatic.java
Added some Object Oriented Programming codes in JAVA.
> Some more conceptual programs in JAVA

- java/Bubblesort.java
> Bubble Sort

- Python/billcalculator.py
Thank you for reading and accepting my pull request.
This py help to learn python with the inclusion of mathematics. The major help from this py is it will use for splitting the bills at any place.
> Added billcalculator.py

- java/QuickSortAlgorithmJava.java
> Quick sort algorithm added

- java/DateNumber.java
> Date Number

- java/RainElevation.java
- java/Telephone.java
> Rain Elevation

- Python/Spiral_Representation_Fibonacci_(Turtle).py
Fibonacci Series Plotting using Turtle module in Python.
> Data Visualizer for Fibonacci Series.

- c++/ExitPoint.cpp
- c++/MatrixMultiplication.cpp
- c++/ShellRotate.cpp
- c++/SpiralPrint.cpp
- c++/WaveTraversal.cpp
Matrix Multiplication
Spiral print 
Shell Rotate 
Exit Point 
Wave Traversal
> some new codes in c++ added

- java/Worker_Problem.java
Write a class Worker and derive classes DailyWorker and SalariedWorker from it. Everyworker has a name and a salary rate. Write method ComPay (int hours) to compute the weekpay of every worker. A Daily Worker is paid based on the number of days he/she works. The Salaries Worker gets paid the wage for 40 hours a week no matter what the actual hours are.Test this program to calculate the pay of workers. You are expected to use the concept of polymorphism to write this program
> Added a worker problem 

- java/SearchInStrings.java
Hello, I added Searching Question (DSA)
> Added Searching in Strings

- java/SuperStaticFinal.java
Write a class Worker and derive classes DailyWorker and SalariedWorker from it. Everyworker has a name and a salary rate. Write method ComPay (int hours) to compute the weekpay of every worker. A Daily Worker is paid based on the number of days he/she works. The Salaries Worker gets paid the wage for 40 hours a week no matter what the actual hours are.Test this program to calculate the pay of workers. You are expected to use the concept of polymorphism to write this program
> Added SuperStaticFinal.java 

- java/BinarySearch.java
- java/OrderAgnosticBinarySearch.java
Hello, I added Binary Search Algorithm Code (both acending and descending)
> added Binary Search Algorithm

- java/FindMin.java
- java/Find_Numbers_With_Even_Digits.java
- java/LinearSearch.java
- java/SearchIn2dArray.java
- java/SearchInRange.java
Added Linear Search DSA Questions (Finding Min , Finding Max, Getting Even Digits)
> Added LinearSearch Questions

- java/ReverseLL.java
Solved reversing a linked list problem in java
> Added reversing a LinkedList

- Python/LCM.py
A python program for calculating LCM of two numbers in python
> Created A Program For Calculating LCM

- java/All_Nodes_Distance_K_in_Binary_Tree.java
> All_Nodes_Distance_K_in_Binary_Tree.java

- C/perfect_number.c
**This PR adds the perfect_number.c program to the C folder in the repository**
> Add : To add perfect_number.c

- Python/merge_sort.py
A new merge Sort algorithm has been added in python
> merge sort in python

- js/bubbleSort.js
> buble sort in js

- js/insertionSort.js
the insertion sort is added in javascript
> feat: add insertion sort

- java/ReverseLetterOnly_Leetcodeq917
Runtime
Details
0ms
Beats 100.00%of users with Java
Memory
Details
40.43MB
Beats 66.36%of users with Java
> added q917 [Reverse Only Letters] [LeetCode]

- java/Remove_Colored_Pieces_LeetCodeq2038.java
- java/ReverseLetterOnly_Leetcodeq917
Added Q2038 , Leetcode , Remove Colored Pieces
Daily Leet 2nd October 2023
> Added Q2038 
